version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_management
    ports:
      - "5432:5432"
    volumes:
      - ./data:$HOME/docker/volumes/postgres
    restart: always